services:
    db:
        image: postgres:17
        restart: unless-stopped
        environment:
            - DATABASE_HOST=db
            - POSTGRES_DB=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
        volumes: 
            - ./.devcontainer/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    app:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
            args:
                  # overwrites default BASE_X values from Dockerfile
                - BASE_REPOSITORY=janrother
                - BASE_IMAGE=tac-environment
                - BASE_ENVIRONMENT=creation
                - BASE_RELEASE=latest
        environment:
            - PGHOST=db
            - PGPORT=5432
            - PGDATABASE=test
            - PGUSER=root
            - PGPASSWORD=root
        ports:
            - "8000:8000"
